[dependencies]
base = "0.10.4"
CanDB = "https://github.com/vporton/CanDB#no-blob-dev@5582b6d383a9587acb2338baed025406e1d6a229"
stable-buffer = "https://github.com/canscale/StableBuffer#v0.2.0"
stablebuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
stable-rbtree = "1.0.0"
btree = "https://github.com/canscale/StableHeapBTreeMap#v0.3.3"
candy = "0.3.0"
